# application: chat-webhook-responder
# version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: 2.3.5
- name: webapp2
  version: 2.5.1

handlers:
- url: /.*
  script: main.APP

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
- ^(.*/)?.*\.md$
